mutation createNewEpic($name: String!, $desc: String, $projectId: ID!) {
    addEpic(input: [{ name: $name, description: $desc, project: { id: $projectId }, tasks: [] }]) {
        numUids
        epic {
            id
            name
            description
            project {
                id
            }
        }
    }
}

query getProjectEpics($projectId: ID!) {
    queryProject(filter: { id: [$projectId] }) {
        epics {
            id
            name
            description
            project {
                id
            }
        }
    }
}

mutation deleteEpicById($idArr: [ID!]) {
    deleteEpic(filter: { id: $idArr }) {
        numUids
        msg
    }
}

mutation editEpic($epicId: ID!, $desc: String) {
    updateEpic(input: { filter: { id: [$epicId] }, set: { description: $desc } }) {
        numUids
        epic {
            id
            name
            description
            project {
                id
            }
        }
    }
}
